import React, { useState } from 'react';
import { api } from './api';

const VIEWS=[['FRONTAL','Front'],['THREE_QUARTER_LEFT','Slight left'],['THREE_QUARTER_RIGHT','Slight right'],['PROFILE_LEFT','Left profile'],['PROFILE_RIGHT','Right profile']];
const labels=Object.fromEntries(VIEWS);
const encode=file=>new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok({name:file.name,mimeType:file.type,contentBase64:String(r.result).split(',')[1]});r.onerror=bad;r.readAsDataURL(file);});
export function AvatarStudioV1Intake({brands,onCreated}) {
 const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(null),[avatar,setAvatar]=useState(null),[coverage,setCoverage]=useState(null),[photos,setPhotos]=useState([]);
 const [form,setForm]=useState({brandId:'',vertical:'PSYCHOLOGY_WELLBEING',name:'',subjectType:'REAL',ageClass:'',role:'Creator'}),set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const request=async fn=>{setBusy(true);setError(null);try{await fn()}catch(e){setError(e)}finally{setBusy(false)}};
 const create=()=>request(async()=>{const a=await api('/api/avatar-studio/avatars',{method:'POST',body:JSON.stringify({internalName:form.name,vertical:form.vertical,brandIds:[form.brandId],subjectType:form.subjectType,ageClass:form.subjectType==='REAL'?form.ageClass:null,intendedChannels:['web'],identity:{agePresentation:'DECLARED_BY_OPERATOR',personality:'TO_BE_DEFINED',role:form.role,languages:['und'],visualDirection:'TO_BE_DEFINED',permanentAttributes:{},prohibitedUses:['unconsented use']},consent:form.subjectType==='SYNTHETIC'?{status:'APPROVED',rightsBasis:'SYNTHETIC_IDENTITY'}:{status:'REVIEW',rightsBasis:'UNVERIFIED_PENDING_CONSENT'},provenance:{source:'AVATAR_STUDIO_V1_SIMPLE_ONBOARDING'}})});setAvatar(a);setStep(2);onCreated?.();});
 const pick=files=>{const p=[...files];if(p.length<1||p.length>10)return setError({code:'IDENTITY_PHOTO_BATCH_INVALID',message:'Choose from 1 to 10 photos.'});if(p.some(x=>!['image/jpeg','image/png','image/webp'].includes(x.type)))return setError({code:'FORMAT_UNSUPPORTED',message:'Use JPEG, PNG, or WebP photos.'});setPhotos(p.map(file=>({file,viewpoint:'UNKNOWN'})));};
 const refresh=async()=>setAvatar(await api(`/api/avatar-studio/avatars/${avatar.id}?brandId=${encodeURIComponent(form.brandId)}`));
 const upload=()=>request(async()=>{const batch=[];for(const p of photos)batch.push({file:await encode(p.file),viewpoint:p.viewpoint});const out=await api(`/api/avatar-studio/avatars/${avatar.id}/identity-photo-batches`,{method:'POST',body:JSON.stringify({brandId:form.brandId,photos:batch})});setCoverage(out.coverage);await refresh();setStep(3);});
 const correct=(id,value)=>request(async()=>{await api(`/api/avatar-studio/avatars/${avatar.id}/source-viewpoints`,{method:'POST',body:JSON.stringify({brandId:form.brandId,sourceId:id,value,humanApproval:true,provenance:{source:'AVATAR_STUDIO_V1_CORRECTION'}})});await refresh();setCoverage(await api(`/api/avatar-studio/avatars/${avatar.id}/identity-coverage?brandId=${encodeURIComponent(form.brandId)}`));});
 const confirm=()=>request(async()=>{const out=await api(`/api/avatar-studio/avatars/${avatar.id}/identity-confirmations`,{method:'POST',body:JSON.stringify({brandId:form.brandId,confirmed:true})});setCoverage(out.coverage);setStep(5);});
 const status=coverage?.status, sources=(avatar?.sources||[]).filter(s=>(s.roles||[]).includes('IDENTITY'));
 return <section className="avatar-wizard v1-intake"><div className="wizard-steps">{['About the person','Add photos','Check coverage','Complete missing views','Ready'].map((n,i)=><span key={n} className={step===i+1?'active':step>i+1?'done':''}>Step {i+1} · {n}</span>)}</div>{error&&<div className="error-panel"><strong>{error.code||'REQUEST_FAILED'}</strong><p>{error.message}</p></div>}
 {step===1&&<div className="panel avatar-form"><h2>Create Avatar</h2><p>Age class is declared for a real person; it is never inferred from a photo.</p><div className="form-grid"><label>Display name<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Brand<select value={form.brandId} onChange={e=>set('brandId',e.target.value)}><option value="">Choose brand</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Subject type<select value={form.subjectType} onChange={e=>set('subjectType',e.target.value)}><option value="REAL">Real person</option><option value="SYNTHETIC">Synthetic</option></select></label>{form.subjectType==='REAL'&&<label>Age class<select value={form.ageClass} onChange={e=>set('ageClass',e.target.value)}><option value="">Declare age class</option><option>ADULT</option><option>MINOR</option></select></label>}</div><button className="primary" disabled={busy||!form.name||!form.brandId||(form.subjectType==='REAL'&&!form.ageClass)} onClick={create}>CREATE AVATAR</button></div>}
 {step===2&&<div className="panel avatar-form"><h2>Add photos</h2><p>Add 1–10 clear photos. Choose each view; this is guided labeling, not face recognition.</p><label className="drop-zone"><strong>ADD PHOTOS</strong><input aria-label="Add identity photos" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>pick(e.target.files)}/></label>{photos.length>0&&<><div className="v1-photo-choices">{photos.map((p,i)=><label key={p.file.name+i}>{p.file.name}<select value={p.viewpoint} onChange={e=>setPhotos(x=>x.map((q,n)=>n===i?{...q,viewpoint:e.target.value}:q))}><option value="UNKNOWN">Which view is this?</option>{VIEWS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>)}</div><button className="primary" disabled={busy} onClick={upload}>ANALYZE AND ADD PHOTOS</button></>}</div>}
 {step>=3&&<div className="panel avatar-form"><h2>Check coverage</h2>{sources.map(s=><article className="v1-photo-card" key={s.id}><img alt="Uploaded identity source" src={`/api/avatar-studio/intakes/${encodeURIComponent(s.intakeAssetId)}/content?brandId=${encodeURIComponent(form.brandId)}&avatarId=${encodeURIComponent(avatar.id)}`}/><div><strong>{labels[s.effectiveViewpoint]||'Needs view label'}</strong><small>Gate 0: {s.gate0Status} · SHA {String(s.contentHash||'').slice(0,12)}</small><label>Correct view<select value={s.effectiveViewpoint||'UNKNOWN'} onChange={e=>correct(s.id,e.target.value)} disabled={busy}><option value="UNKNOWN">Which view is this?</option>{VIEWS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></article>)}<div className="v1-coverage">{VIEWS.map(([v,l])=><span key={v}>{coverage?.coverage?.[v]?'✓':'—'} {l}</span>)}</div>{status==='NOT_READY'&&<p><strong>NOT READY</strong><br/>We still need: {(coverage?.missingRequired||[]).map(v=>labels[v]).join(', ')}.</p>}{status==='READY_FOR_IDENTITY_LOCK'&&<p><strong>READY FOR IDENTITY LOCK</strong><br/>Optional for stronger consistency: {(coverage?.missingRecommended||[]).map(v=>labels[v]).join(', ')}.</p>}{status==='STRONG_COVERAGE'&&<p><strong>STRONG COVERAGE</strong></p>}{status&&status!=='NOT_READY'&&step!==5&&<button className="primary" disabled={busy} onClick={confirm}>I CONFIRM THESE PHOTOS SHOW THE INTENDED PERSON</button>}</div>}
 {step===5&&<div className="panel avatar-form"><h2>Ready</h2><strong>READY FOR IDENTITY LOCK</strong><p>Identity Lock creation has not been performed here.</p></div>}</section>;
}
