import React, { useEffect, useMemo, useState } from 'react';
import { api } from './api';

const ENGINES = { HEYGEN: 'AVATAR_IV', TAVUS: 'TAVUS_REPLICA', DID: 'DID_SCENE' };

export function AvatarProviderBenchmark({ brands }) {
  const [brandId, setBrandId] = useState(''); const [avatars, setAvatars] = useState([]); const [avatarId, setAvatarId] = useState('');
  const [avatar, setAvatar] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState(null); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ script: 'Take one calm breath.', audioArtifactId: '', audioArtifactVersion: '1', audioContentHash: '', language: 'en' });
  useEffect(() => { if (!brandId) { setAvatars([]); setAvatarId(''); return; } api(`/api/avatar-studio/avatars?brandId=${encodeURIComponent(brandId)}`).then(setAvatars).catch(setError); }, [brandId]);
  useEffect(() => { if (!avatarId || !brandId) { setAvatar(null); return; } api(`/api/avatar-studio/avatars/${avatarId}?brandId=${encodeURIComponent(brandId)}`).then(setAvatar).catch(setError); }, [avatarId, brandId]);
  const bindings = useMemo(() => ['HEYGEN','TAVUS','DID'].map((provider) => avatar?.providerBindings?.find((item) => item.provider === provider && item.status === 'ACTIVE') || null), [avatar]);
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  async function prepare(event) { event.preventDefault(); if (!avatar) return; setBusy(true); setError(null); try {
    setResult(await api(`/api/avatar-studio/avatars/${avatar.id}/avatar-provider-benchmark`, { method: 'POST', body: JSON.stringify({ brandId, bindings: bindings.filter(Boolean), commonIntent: {
      script: form.script, audioStrategy: 'EXTERNAL_AUDIO', audioArtifact: { artifactId: form.audioArtifactId, artifactVersion: Number(form.audioArtifactVersion), contentHash: form.audioContentHash }, language: form.language,
      framing: 'CHEST_UP', aspectRatio: '9:16', durationPolicy: { requestedSeconds: 5 }, performanceProfile: 'IMPULSEOFF_CALM_SELF_V1', expressionTarget: 'CALM_ATTENTIVE', gestureIntensity: 'MINIMAL', cameraPolicy: 'LOCKED_OR_NEARLY_LOCKED', backgroundPolicy: 'APPROVED_NEUTRAL', outputFormat: 'MP4', qaProfile: 'AVATAR_PERFORMANCE_V1', providerEngines: ENGINES,
    } }) }));
  } catch (cause) { setError(cause); } finally { setBusy(false); } }
  return <section className="avatar-provider-benchmark panel"><header><span className="eyebrow">PRE-RENDERED AVATAR PERFORMANCE</span><h2>Provider Benchmark</h2><p>One canonical identity and performance intent. Every card is an explicit provider binding; no AUTO route, fallback, or live event generation.</p></header>{error ? <div className="error-panel"><strong>{error.code}</strong><p>{error.message}</p></div> : null}<form className="avatar-form" onSubmit={prepare}><div className="form-grid"><label>Brand<select value={brandId} onChange={(event) => setBrandId(event.target.value)} required><option value="">Choose brand</option>{brands.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Avatar<select value={avatarId} onChange={(event) => setAvatarId(event.target.value)} required><option value="">Choose avatar</option>{avatars.map((item) => <option key={item.id} value={item.id}>{item.internalName}</option>)}</select></label><label>Approved external audio artifact<input value={form.audioArtifactId} onChange={(event) => change('audioArtifactId', event.target.value)} required /></label><label>Audio artifact version<input type="number" min="1" value={form.audioArtifactVersion} onChange={(event) => change('audioArtifactVersion', event.target.value)} required /></label><label>Audio content hash<input value={form.audioContentHash} onChange={(event) => change('audioContentHash', event.target.value)} required /></label><label>Language<input value={form.language} onChange={(event) => change('language', event.target.value)} required /></label></div><label>Approved semantic script<textarea value={form.script} onChange={(event) => change('script', event.target.value)} required /></label><div className="benchmark-binding-grid">{['HEYGEN','TAVUS','DID'].map((provider, index) => { const item = bindings[index]; return <article key={provider} className={item ? 'ready' : 'blocked'}><strong>{provider}</strong><code>{item ? `${item.providerBindingType} · rev ${item.bindingRevision}` : 'ACTIVE BINDING REQUIRED'}</code><small>{item?.providerExternalId || 'No provider substitution'}</small></article>; })}</div><button className="primary" disabled={busy || bindings.some((item) => !item)}>{busy ? 'PREPARING…' : 'PREPARE THREE PROVIDER PREFLIGHTS'}</button></form>{result ? <section className="benchmark-results">{result.executions.map((item) => <article key={item.provider}><strong>{item.provider}</strong><span>{item.preflight.readiness}</span><code>{item.preflight.contract.providerEngine}</code><small>{item.deviation ? JSON.stringify(item.deviation) : 'No declared capability deviation'}</small></article>)}</section> : null}</section>;
}
