import React, { useEffect, useState } from 'react';
import { api } from './api';

const VIEWS=[['FRONTAL','Front'],['THREE_QUARTER_LEFT','Slight left'],['THREE_QUARTER_RIGHT','Slight right'],['PROFILE_LEFT','Left profile'],['PROFILE_RIGHT','Right profile']];
const labels=Object.fromEntries(VIEWS);
const encode=file=>new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok({name:file.name,mimeType:file.type,contentBase64:String(r.result).split(',')[1]});r.onerror=bad;r.readAsDataURL(file);});
const imageSize=file=>`${(file.size/(1024*1024)).toFixed(file.size>=1024*1024?1:2)} MB`;
const MAX_UPLOAD_FILE_BYTES=25*1024*1024;
export function AvatarStudioV1Intake({brands,onCreated,onIdentityLock}) {
 const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(null),[avatar,setAvatar]=useState(null),[coverage,setCoverage]=useState(null),[photos,setPhotos]=useState([]),[setupMode,setSetupMode]=useState(null),[candidates,setCandidates]=useState([]),[persisted,setPersisted]=useState([]),[persistedViews,setPersistedViews]=useState({});
 const [form,setForm]=useState({brandId:'',vertical:'PSYCHOLOGY_WELLBEING',name:'',subjectType:'REAL',ageClass:'',role:'Creator',rights:'SELF',subjectName:'',rightsNotes:''}),set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const request=async fn=>{setBusy(true);setError(null);try{await fn()}catch(e){setError(e)}finally{setBusy(false)}};
 useEffect(()=>{if(!form.brandId||setupMode)return;api(`/api/avatar-studio/avatar-setups?brandId=${encodeURIComponent(form.brandId)}`).then(setCandidates).catch(setError);},[form.brandId,setupMode]);
 const resume=id=>request(async()=>{const state=await api(`/api/avatar-studio/avatars/${id}/identity-setup?brandId=${encodeURIComponent(form.brandId)}`);setAvatar(state.avatar);setCoverage(state.coverage);setPersisted((state.intakes||[]).map(item=>({...item,used:(state.avatar.sources||[]).some(source=>source.intakeAssetId===item.id&&(source.roles||[]).includes('IDENTITY'))})));setStep({RIGHTS_CONSENT:2,ADD_PHOTOS:3,CHECK_COVERAGE:4,READY:5}[state.next]||3);setSetupMode('CONTINUE');});
 const usePersisted=id=>request(async()=>{const view=persistedViews[id]||'UNKNOWN';if(view==='UNKNOWN')throw new Error('Choose the view shown in this photo.');const out=await api(`/api/avatar-studio/avatars/${avatar.id}/identity-photo-batches`,{method:'POST',body:JSON.stringify({brandId:form.brandId,photos:[{intakeId:id,viewpoint:view}]})});setCoverage(out.coverage);setPersisted(items=>items.map(item=>item.id===id?{...item,used:true}:item));await refresh();});
 const create=()=>request(async()=>{const a=await api('/api/avatar-studio/avatars',{method:'POST',body:JSON.stringify({internalName:form.name,vertical:form.vertical,brandIds:[form.brandId],subjectType:form.subjectType,ageClass:form.subjectType==='REAL'?form.ageClass:null,intendedChannels:['web'],identity:{agePresentation:'DECLARED_BY_OPERATOR',personality:'TO_BE_DEFINED',role:form.role,languages:['und'],visualDirection:'TO_BE_DEFINED',permanentAttributes:{},prohibitedUses:['unconsented use']},consent:form.subjectType==='SYNTHETIC'?{status:'APPROVED',rightsBasis:'SYNTHETIC_IDENTITY'}:{status:'REVIEW',rightsBasis:'UNVERIFIED_PENDING_CONSENT'},provenance:{source:'AVATAR_STUDIO_V1_SIMPLE_ONBOARDING'}})});setAvatar(a);setStep(form.subjectType==='REAL'?2:3);onCreated?.();});
 const grantRights=()=>request(async()=>{await api(`/api/avatar-studio/avatars/${avatar.id}/identity-rights-consent`,{method:'POST',body:JSON.stringify({brandId:form.brandId,ownerRelationship:form.rights,subjectName:form.subjectName,evidenceNotes:form.rightsNotes,humanApproval:true,disclosureAccepted:true})});setAvatar(await api(`/api/avatar-studio/avatars/${avatar.id}?brandId=${encodeURIComponent(form.brandId)}`));setStep(3);});
 const pick=files=>{const p=[...files];if(p.length<1||p.length>10)return setError({code:'IDENTITY_PHOTO_BATCH_INVALID',message:'Choose from 1 to 10 photos.'});setPhotos(p.map(file=>({file,viewpoint:'UNKNOWN',preview:URL.createObjectURL(file),intakeId:null,status:!['image/jpeg','image/png','image/webp'].includes(file.type)?'INVALID':file.size>MAX_UPLOAD_FILE_BYTES?'TOO_LARGE':'READY',error:null})));};
 const refresh=async()=>setAvatar(await api(`/api/avatar-studio/avatars/${avatar.id}?brandId=${encodeURIComponent(form.brandId)}`));
 const upload=()=>request(async()=>{let current=[...photos];for(let index=0;index<current.length;index+=1){const photo=current[index];if(photo.intakeId||photo.status==='INVALID'||photo.status==='TOO_LARGE')continue;try{const result=await api(`/api/avatar-studio/avatars/${avatar.id}/intakes`,{method:'POST',body:JSON.stringify({brandId:form.brandId,sourceType:'UPLOAD',file:await encode(photo.file),provenance:{intakeFlow:'AVATAR_STUDIO_V1_IDENTITY_UPLOAD',visualOnly:true}})});current=current.map((item,n)=>n===index?{...item,intakeId:result.asset.id,status:'UPLOADED',error:null,preview:result.asset.previewUrl}:item);setPhotos(current);}catch(cause){current=current.map((item,n)=>n===index?{...item,status:'FAILED',error:cause.message||'Photo could not be uploaded.'}:item);setPhotos(current);}}
   if(current.some(photo=>photo.status==='FAILED'))throw new Error('Some photos could not be uploaded. Retry only the failed photo cards; successful photos are already saved.');const ready=current.filter(photo=>photo.intakeId).map(photo=>({intakeId:photo.intakeId,viewpoint:photo.viewpoint}));if(!ready.length)throw new Error('Upload at least one valid photo before checking coverage.');const out=await api(`/api/avatar-studio/avatars/${avatar.id}/identity-photo-batches`,{method:'POST',body:JSON.stringify({brandId:form.brandId,photos:ready})});setCoverage(out.coverage);await refresh();setStep(4);});
 const correct=(id,value)=>request(async()=>{await api(`/api/avatar-studio/avatars/${avatar.id}/source-viewpoints`,{method:'POST',body:JSON.stringify({brandId:form.brandId,sourceId:id,value,humanApproval:true,provenance:{source:'AVATAR_STUDIO_V1_CORRECTION'}})});await refresh();setCoverage(await api(`/api/avatar-studio/avatars/${avatar.id}/identity-coverage?brandId=${encodeURIComponent(form.brandId)}`));});
 const confirm=()=>request(async()=>{const out=await api(`/api/avatar-studio/avatars/${avatar.id}/identity-confirmations`,{method:'POST',body:JSON.stringify({brandId:form.brandId,confirmed:true})});setCoverage(out.coverage);setStep(5);});
 const status=coverage?.status, sources=(avatar?.sources||[]).filter(s=>(s.roles||[]).includes('IDENTITY'));
 if(!setupMode)return <section className="avatar-wizard v1-intake"><div className="panel avatar-form"><h2>Avatar Setup</h2><label>Brand<select value={form.brandId} onChange={e=>set('brandId',e.target.value)}><option value="">Choose brand</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{form.brandId&&<><h3>Continue Setup</h3>{candidates.length?candidates.map(item=><article className="v1-photo-card" key={item.id}><div><strong>{item.internalName}</strong><small>{item.subjectType==='SYNTHETIC'?'Synthetic':'Real person'} · {item.vertical}</small><button onClick={()=>resume(item.id)}>CONTINUE</button></div></article>):<p>No incomplete avatars for this brand.</p>}<button className="primary" onClick={()=>setSetupMode('NEW')}>START NEW</button></>}</div>{error&&<div className="error-panel"><strong>{error.code||'REQUEST_FAILED'}</strong><p>{error.message}</p></div>}</section>;
 return <section className="avatar-wizard v1-intake"><div className="wizard-steps">{['About the person','Rights & Consent','Add photos','Check coverage','Ready'].map((n,i)=><span key={n} className={step===i+1?'active':step>i+1?'done':''}>Step {i+1} · {n}</span>)}</div>{avatar&&<p className="page-note">Setting up: <strong>{avatar.internalName}</strong> · {avatar.subjectType==='SYNTHETIC'?'Synthetic':'Real person'} · {avatar.provenance?.ageClass||form.ageClass||'Declared'}</p>}{error&&<div className="error-panel"><strong>{error.code||'REQUEST_FAILED'}</strong><p>{error.message}</p></div>}
 {step===1&&<div className="panel avatar-form"><h2>Create Avatar</h2><p>Age class is declared for a real person; it is never inferred from a photo.</p><div className="form-grid"><label>Display name<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Brand<select value={form.brandId} onChange={e=>set('brandId',e.target.value)}><option value="">Choose brand</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Subject type<select value={form.subjectType} onChange={e=>set('subjectType',e.target.value)}><option value="REAL">Real person</option><option value="SYNTHETIC">Synthetic</option></select></label>{form.subjectType==='REAL'&&<label>Age class<select value={form.ageClass} onChange={e=>set('ageClass',e.target.value)}><option value="">Declare age class</option><option>ADULT</option><option>MINOR</option></select></label>}</div><button className="primary" disabled={busy||!form.name||!form.brandId||(form.subjectType==='REAL'&&!form.ageClass)} onClick={create}>CREATE AVATAR</button></div>}
 {step===2&&<div className="panel avatar-form"><h2>Rights &amp; Consent</h2><p>Confirm rights and face consent before using photos to build this avatar. This applies only to this avatar, brand, audience and displayed use.</p><div className="form-grid"><label>Rights relationship<select value={form.rights} onChange={e=>set('rights',e.target.value)}>{form.ageClass==='MINOR'?<option value="GUARDIAN_AUTHORIZED">Guardian or authorized rights holder</option>:<><option value="SELF">This is me</option><option value="AUTHORIZED_BY_SUBJECT">I have explicit permission</option></>}</select></label><label>Person shown<input value={form.subjectName} onChange={e=>set('subjectName',e.target.value)}/></label><label>Attestation note<input value={form.rightsNotes} onChange={e=>set('rightsNotes',e.target.value)}/></label></div><p>{form.rights==='SELF'?'I confirm that I am the person shown and consent to FACE use for this avatar.':form.rights==='GUARDIAN_AUTHORIZED'?'I confirm that I am the guardian or authorized rights holder for this minor.':'I confirm that I have explicit permission from the person shown.'}</p><button className="primary" disabled={busy||!form.subjectName||!form.rightsNotes} onClick={grantRights}>CONTINUE WITH FACE CONSENT</button></div>}
 {step===3&&<div className="panel avatar-form"><h2>Add / Manage Photos</h2>{coverage?.status!=='NOT_READY'&&<button className="primary" onClick={()=>setStep(coverage?.status==='STRONG_COVERAGE'||coverage?.status==='READY_FOR_IDENTITY_LOCK'?5:4)}>CONTINUE TO IDENTITY LOCK</button>}{coverage?.status==='NOT_READY'&&<button className="secondary" onClick={()=>setStep(4)}>BACK TO CHECK COVERAGE</button>}{persisted.length?<><h3>Existing uploaded photos</h3>{persisted.map(item=><article className="v1-photo-card" key={item.id}><img alt={`Persisted photo ${item.originalFilename}`} src={item.previewUrl}/><div><strong>{item.originalFilename}</strong><small>Uploaded · {item.byteSize} bytes · Gate 0: {item.effectiveGate0Status} · {item.used?'Already used as identity':'Not yet used for identity'}</small>{!item.used&&item.effectiveGate0Status==='PASS'&&<><label>View<select value={persistedViews[item.id]||'UNKNOWN'} onChange={e=>setPersistedViews(old=>({...old,[item.id]:e.target.value}))}><option value="UNKNOWN">Which view is this?</option>{VIEWS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button disabled={busy} onClick={()=>usePersisted(item.id)}>USE FOR IDENTITY</button></>}</div></article>)}</>:null}<h3>Add more photos</h3><label className="drop-zone"><strong>ADD PHOTOS</strong><input aria-label="Add identity photos" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>pick(e.target.files)}/></label>{photos.length>0&&<><div className="v1-photo-choices">{photos.map((p,i)=><article className="v1-selected-photo" key={p.file.name+i}><img alt={`Selected photo ${p.file.name}`} src={p.preview}/><strong>{p.file.name}</strong><small>{imageSize(p.file)}</small><label>View<select aria-label={`View for ${p.file.name}`} value={p.viewpoint} onChange={e=>setPhotos(x=>x.map((q,n)=>n===i?{...q,viewpoint:e.target.value}:q))}><option value="UNKNOWN">Which view is this?</option>{VIEWS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></article>)}</div><button className="primary" disabled={busy} onClick={upload}>UPLOAD PHOTOS AND CHECK COVERAGE</button></>}</div>}
 {step>=4&&<div className="panel avatar-form"><h2>Check coverage</h2><button className="secondary" onClick={()=>setStep(3)}>ADD / MANAGE PHOTOS</button>{sources.map(s=><article className="v1-photo-card" key={s.id}><img alt="Uploaded identity source" src={`/api/avatar-studio/intakes/${encodeURIComponent(s.intakeAssetId)}/content?brandId=${encodeURIComponent(form.brandId)}&avatarId=${encodeURIComponent(avatar.id)}`}/><div><strong>{labels[s.effectiveViewpoint]||'Needs view label'}</strong><small>Gate 0: {s.gate0Status} · SHA {String(s.contentHash||'').slice(0,12)}</small><label>Correct view<select value={s.effectiveViewpoint||'UNKNOWN'} onChange={e=>correct(s.id,e.target.value)} disabled={busy}><option value="UNKNOWN">Which view is this?</option>{VIEWS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></article>)}<div className="v1-coverage">{VIEWS.map(([v,l])=><span key={v}>{coverage?.coverage?.[v]?'✓':'—'} {l}</span>)}</div>{status==='NOT_READY'&&<p><strong>NOT READY</strong><br/>We still need: {(coverage?.missingRequired||[]).map(v=>labels[v]).join(', ')}.</p>}{status==='READY_FOR_IDENTITY_LOCK'&&<p><strong>READY FOR IDENTITY LOCK</strong><br/>Optional for stronger consistency: {(coverage?.missingRecommended||[]).map(v=>labels[v]).join(', ')}.</p>}{status==='STRONG_COVERAGE'&&<p><strong>STRONG COVERAGE</strong></p>}{status&&status!=='NOT_READY'&&step!==5&&<button className="primary" disabled={busy} onClick={confirm}>I CONFIRM THESE PHOTOS SHOW THE INTENDED PERSON</button>}</div>}
 {step===5&&<div className="panel avatar-form"><h2>Ready</h2><strong>READY FOR IDENTITY LOCK</strong><p>Continue with the same avatar and brand.</p><button className="primary" onClick={()=>onIdentityLock?.({avatar,brandId:form.brandId})}>CONTINUE TO IDENTITY LOCK</button><button className="secondary" onClick={()=>setStep(3)}>MANAGE PHOTOS</button><button className="secondary" onClick={()=>setSetupMode(null)}>VIEW IN LIBRARY</button></div>}</section>;
}
