import React, { useEffect, useState } from 'react';
import { api } from './api';
import { IDENTITY_VIEWPOINTS } from './IdentitySourceTools';

const VERTICAL_LABELS = {
  PSYCHOLOGY_WELLBEING:'Psychology & Wellbeing',CONSTRUCTION_RENOVATION:'Construction & Renovation',
  LUXURY_LIFESTYLE:'Luxury Lifestyle',TRAVEL:'Travel',
};
const IMAGE_TYPES = new Set(['image/jpeg','image/png','image/webp']);

function Badge({ value }) { return <span className={`avatar-badge avatar-${String(value||'').toLowerCase()}`}>{String(value||'NOT STARTED').replaceAll('_',' ')}</span>; }
function ErrorPanel({ error }) { return error?<div className="error-panel"><strong>{error.code}</strong><p>{error.message}</p></div>:null; }
function Select({label,value,onChange,children,required=true}) { return <label>{label}<select aria-label={label} required={required} value={value} onChange={(event)=>onChange(event.target.value)}>{children}</select></label>; }
function Input({label,value,onChange,required=true}) { return <label>{label}<input aria-label={label} required={required} value={value} onChange={(event)=>onChange(event.target.value)}/></label>; }
function filePayload(file) { return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>resolve({name:file.name,mimeType:file.type,contentBase64:String(reader.result).split(',')[1],capturedAt:new Date().toISOString()});reader.readAsDataURL(file);}); }
function classifications(value) { return Object.fromEntries(String(value).split(',').map((item)=>item.trim()).filter(Boolean).map((item)=>{const [key,...rest]=item.split('=');return [key.trim(),rest.join('=').trim()||'explicit operator classification'];})); }

export function CreateAvatarMultiSource({ brands,onCreated }) {
  const [step,setStep]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState(null);
  const [avatar,setAvatar]=useState(null); const [intake,setIntake]=useState(null); const [mode,setMode]=useState('UPLOAD');
  const [existing,setExisting]=useState([]); const [existingId,setExistingId]=useState(''); const [safeUrl,setSafeUrl]=useState('');
  const [roles,setRoles]=useState(['IDENTITY','PASSPORT_SOURCE']); const [capture,setCapture]=useState(null);
  const [consentEvidence,setConsentEvidence]=useState(null); const [consentLink,setConsentLink]=useState(null);
  const [batch,setBatch]=useState([]); const [batchIndex,setBatchIndex]=useState(-1); const [attachedCount,setAttachedCount]=useState(0);
  const [form,setForm]=useState({vertical:'PSYCHOLOGY_WELLBEING',brandId:'',internalName:'',subjectType:'SYNTHETIC',role:'',intendedChannels:'Instagram Reels',
    agePresentation:'',personality:'',languages:'en',visualDirection:'',prohibitedUses:'deception, political endorsement',consentName:'',consentBasis:'SIGNED_RELEASE',
    consentEvidence:'',consentDisclosure:false,lockPermanent:'facialStructure=preserve, apparentAge=preserve, nose=preserve, jaw=preserve, hairline=preserve',
    lockTemporary:'hat=exclude, jacket=exclude, wardrobe=exclude, background=exclude, lighting=exclude',lockUncertain:'glasses=operator decision'});
  const change=(key,value)=>setForm((current)=>({...current,[key]:value}));
  const steps=['Context','Asset intake','Gate 0 + consent','Identity','Identity Lock','Passport Lab ready'];
  useEffect(()=>{if(mode!=='EXISTING_ASSET'||!avatar)return;api(`/api/avatar-studio/avatars/${avatar.id}/existing-assets?brandId=${encodeURIComponent(form.brandId)}`).then(setExisting).catch(setError);},[mode,avatar,form.brandId]);

  async function startDraft(){setBusy(true);setError(null);try{const created=await api('/api/avatar-studio/avatars',{method:'POST',body:JSON.stringify({
    vertical:form.vertical,brandIds:[form.brandId],internalName:form.internalName,subjectType:form.subjectType,
    intendedChannels:form.intendedChannels.split(',').map((item)=>item.trim()),identity:{agePresentation:'TO_BE_DEFINED',personality:'TO_BE_DEFINED',role:form.role,languages:['und'],visualDirection:'TO_BE_DEFINED',permanentAttributes:{},prohibitedUses:form.prohibitedUses.split(',').map((item)=>item.trim())},
    consent:form.subjectType==='SYNTHETIC'?{status:'APPROVED',rightsBasis:'SYNTHETIC_IDENTITY'}:{status:'REVIEW',rightsBasis:'UNVERIFIED_PENDING_CONSENT'},
    provenance:{source:'AVATAR_STUDIO_INTAKE_DRAFT',identityState:'PROVISIONAL'}})});setAvatar(created);setStep(1);}catch(cause){setError(cause);}finally{setBusy(false);}}

  function stagePhotos(fileList){const files=[...(fileList||[])];if(!files.length)return;if(files.length>10){setError({code:'SOURCE_SET_TOO_LARGE',message:'Choose at most 10 initial identity photographs.'});return;}
    const invalid=files.find((file)=>!IMAGE_TYPES.has(String(file.type||'').toLowerCase()));if(invalid){setError({code:'FORMAT_UNSUPPORTED',message:`${invalid.name} is unsupported. Initial multi-photo intake accepts JPEG/JPG, PNG and WebP.`});return;}
    setError(null);setBatch(files.map((file,index)=>({id:`initial-${Date.now()}-${index}`,file,viewpoint:'UNKNOWN'})));setBatchIndex(-1);setAttachedCount(0);}

  async function submitIntake({file=null,sourceType=mode,viewpoint='UNKNOWN',avatarValue=avatar}={}){setBusy(true);setError(null);try{const payload={brandId:form.brandId,sourceType,
    provenance:{owner:form.subjectType==='SYNTHETIC'?'SYNTHETIC':'OPERATOR_SUPPLIED',source:'AVATAR_STUDIO_BROWSER_INTAKE',identityViewpoint:viewpoint,
      sourceSetClass:batch.length?'INITIAL_MULTI_SOURCE':'SINGLE_SOURCE',visualOnly:sourceType==='CAMERA'}};
    if(file)payload.file=await filePayload(file);if(sourceType==='EXISTING_ASSET')payload.existingAssetId=existingId;if(sourceType==='SAFE_URL_IMPORT')payload.url=safeUrl;
    const result=await api(`/api/avatar-studio/avatars/${avatarValue.id}/intakes`,{method:'POST',body:JSON.stringify(payload)});setIntake(result);setStep(2);return result;
  }catch(cause){setError(cause);return null;}finally{setBusy(false);}}

  async function beginBatch(){if(!batch.length)return;setBatchIndex(0);await submitIntake({file:batch[0].file,sourceType:'UPLOAD',viewpoint:batch[0].viewpoint});}

  async function submitConsentEvidence(file,sourceType){setBusy(true);setError(null);try{const result=await api(`/api/avatar-studio/avatars/${avatar.id}/intakes`,{method:'POST',body:JSON.stringify({brandId:form.brandId,sourceType,file:await filePayload(file),provenance:{owner:'SELF_RECORDED_CONSENT',source:'LOCAL_CONSENT_CAPTURE'}})});setConsentEvidence(result.asset);}catch(cause){setError(cause);}finally{setBusy(false);}}
  async function startCapture(kind,consentEvidenceCapture=false){setError(null);try{const stream=await navigator.mediaDevices.getUserMedia(kind==='CAMERA'?{video:true,audio:false}:{audio:true});const chunks=[];const recorder=new MediaRecorder(stream);recorder.ondataavailable=(event)=>event.data.size&&chunks.push(event.data);recorder.onstop=async()=>{const mimeType=recorder.mimeType||(kind==='CAMERA'?'video/webm':'audio/webm');const file=new File(chunks,`${kind.toLowerCase()}-${Date.now()}.webm`,{type:mimeType});stream.getTracks().forEach((track)=>track.stop());setCapture(null);if(consentEvidenceCapture)await submitConsentEvidence(file,kind);else await submitIntake({file,sourceType:kind});};recorder.start();setCapture({kind,recorder,consentEvidence:consentEvidenceCapture});}catch(cause){setError({code:'CAPTURE_UNAVAILABLE',message:cause.message});}}

  async function review(action){setBusy(true);setError(null);try{const result=await api(`/api/avatar-studio/avatars/${avatar.id}/intakes/${intake.asset.id}/review`,{method:'POST',body:JSON.stringify({brandId:form.brandId,action,reason:action==='APPROVE_FOR_USE'?'Operator reviewed all Gate 0 findings and approved this exact immutable version.':'Operator verified rights evidence.',humanApproval:true})});setIntake((current)=>({...current,asset:result.asset,sourceReadiness:result.asset.sourceReadiness,gate0:{...current.gate0,status:result.asset.effectiveGate0Status}}));}catch(cause){setError(cause);}finally{setBusy(false);}}
  async function grantConsent(){setBusy(true);setError(null);try{const result=await api(`/api/avatar-studio/avatars/${avatar.id}/intakes/${intake.asset.id}/consents`,{method:'POST',body:JSON.stringify({brandId:form.brandId,modality:'FACE',subjectIdentity:{name:form.consentName},rightsBasis:form.consentBasis,allowedBrandIds:[form.brandId],allowedVerticals:[form.vertical],allowedChannels:form.intendedChannels.split(',').map((item)=>item.trim()),allowedUseTypes:['AVATAR_IDENTITY','PASSPORT_REFERENCE'],evidenceNotes:form.consentEvidence,evidenceIntakeId:consentEvidence?.id||null,disclosureAccepted:form.consentDisclosure,humanApproval:true})});setIntake((current)=>({...current,asset:result.asset,sourceReadiness:result.asset.sourceReadiness}));const fresh=await api(`/api/avatar-studio/avatars/${avatar.id}?brandId=${encodeURIComponent(form.brandId)}`);setAvatar(fresh);}catch(cause){setError(cause);}finally{setBusy(false);}}
  async function reviewConsentEvidence(){setBusy(true);setError(null);try{const result=await api(`/api/avatar-studio/avatars/${avatar.id}/intakes/${consentEvidence.id}/review`,{method:'POST',body:JSON.stringify({brandId:form.brandId,action:'APPROVE_FOR_USE',reason:'Operator reviewed this exact local consent recording.',humanApproval:true})});setConsentEvidence(result.asset);}catch(cause){setError(cause);}finally{setBusy(false);}}
  async function requestRemoteConsent(){setBusy(true);setError(null);try{setConsentLink(await api(`/api/avatar-studio/avatars/${avatar.id}/intakes/${intake.asset.id}/consent-requests`,{method:'POST',body:JSON.stringify({brandId:form.brandId,modality:'FACE',disclosureText:`I consent to use of this exact face reference for ${form.internalName}, ${form.vertical}, brand ${form.brandId}, channels ${form.intendedChannels}.`})}));}catch(cause){setError(cause);}finally{setBusy(false);}}

  async function useSource(){setBusy(true);setError(null);try{await api(`/api/avatar-studio/avatars/${avatar.id}/intakes/${intake.asset.id}/use`,{method:'POST',body:JSON.stringify({brandId:form.brandId,roles})});const nextAttached=attachedCount+1;setAttachedCount(nextAttached);
    if(batch.length&&batchIndex>=0&&batchIndex<batch.length-1){const fresh=await api(`/api/avatar-studio/avatars/${avatar.id}?brandId=${encodeURIComponent(form.brandId)}`);setAvatar(fresh);const next=batchIndex+1;setBatchIndex(next);await submitIntake({file:batch[next].file,sourceType:'UPLOAD',viewpoint:batch[next].viewpoint,avatarValue:fresh});return;}
    setStep(3);
  }catch(cause){setError(cause);}finally{setBusy(false);}}

  async function saveIdentity(){setBusy(true);setError(null);try{const result=await api(`/api/avatar-studio/avatars/${avatar.id}/identity`,{method:'POST',body:JSON.stringify({brandId:form.brandId,identity:{agePresentation:form.agePresentation,personality:form.personality,role:form.role,languages:form.languages.split(',').map((item)=>item.trim()),visualDirection:form.visualDirection,permanentAttributes:{},prohibitedUses:form.prohibitedUses.split(',').map((item)=>item.trim())},provenance:{source:'AVATAR_STUDIO_IDENTITY_AFTER_MULTI_SOURCE_INTAKE',sourceCount:attachedCount||1}})});setAvatar(result.avatar);setStep(4);}catch(cause){setError(cause);}finally{setBusy(false);}}
  async function saveIdentityLock(){setBusy(true);setError(null);try{const result=await api(`/api/avatar-studio/avatars/${avatar.id}/identity-locks`,{method:'POST',body:JSON.stringify({brandId:form.brandId,permanent:classifications(form.lockPermanent),temporary:classifications(form.lockTemporary),uncertain:classifications(form.lockUncertain),notes:'Classified in Create Avatar multi-source wizard',humanApproval:true,provenance:{source:'CREATE_AVATAR_IDENTITY_LOCK_STEP'}})});setAvatar(result.avatar);setStep(5);onCreated();}catch(cause){setError(cause);}finally{setBusy(false);}}
  function toggleRole(role){setRoles((current)=>current.includes(role)?current.filter((item)=>item!==role):[...current,role]);}
  const gateStatus=intake?.asset?.effectiveGate0Status||intake?.gate0?.status;const readiness=intake?.asset?.sourceReadiness||intake?.sourceReadiness||(gateStatus==='PASS'?{state:'SOURCE READY',reason:'The source decoded successfully and passed the current technical and Gate 0 checks.'}:{state:'REVIEW REQUIRED',reason:'Review the bounded intake findings.'});

  return <section className="avatar-wizard"><div className="wizard-steps">{steps.map((name,index)=><span className={step===index?'active':index<step?'done':''} key={name}>{index+1} · {name}</span>)}</div><ErrorPanel error={error}/>
    {step===0?<div className="panel avatar-form"><h2>Context</h2><div className="form-grid"><Select label="Audience vertical" value={form.vertical} onChange={(v)=>change('vertical',v)}>{Object.entries(VERTICAL_LABELS).map(([code,label])=><option value={code} key={code}>{label}</option>)}</Select><Select label="Allowed brand" value={form.brandId} onChange={(v)=>change('brandId',v)}><option value="">Choose brand</option>{brands.map((brand)=><option key={brand.id} value={brand.id}>{brand.name}</option>)}</Select><Select label="Identity source type" value={form.subjectType} onChange={(v)=>change('subjectType',v)}><option>SYNTHETIC</option><option>FOUNDER</option><option>CONSENTED_REAL_PERSON</option><option>APPROVED_CHARACTER</option></Select><Input label="Internal avatar name" value={form.internalName} onChange={(v)=>change('internalName',v)}/><Input label="Persona role" value={form.role} onChange={(v)=>change('role',v)}/><Input label="Intended channels" value={form.intendedChannels} onChange={(v)=>change('intendedChannels',v)}/></div><button className="primary" disabled={busy||!form.brandId||!form.role||!form.internalName} onClick={startDraft}>{busy?'CREATING DRAFT…':'START ASSET INTAKE'}</button></div>:null}
    {step===1?<div className="panel avatar-form"><h2>Asset intake</h2><p>Add one or several identity photographs. Each exact file is independently versioned and independently passes Gate 0.</p><div className="intake-modes">{['UPLOAD','CAMERA','MICROPHONE','EXISTING_ASSET','SAFE_URL_IMPORT'].map((item)=><button type="button" className={mode===item?'active':''} onClick={()=>setMode(item)} key={item}>{item.replaceAll('_',' ')}</button>)}</div>
      {mode==='UPLOAD'?<><label className="drop-zone"><strong>ADD IDENTITY PHOTOS</strong><span>1–10 files · JPEG/JPG, PNG or WebP · originals are not merged or re-encoded before Gate 0</span><input aria-label="Avatar source files" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event)=>stagePhotos(event.target.files)}/></label>{batch.length?<div className="identity-source-grid">{batch.map((item)=><article key={item.id}><strong>{item.file.name}</strong><label>Viewpoint<select value={item.viewpoint} onChange={(event)=>setBatch((current)=>current.map((entry)=>entry.id===item.id?{...entry,viewpoint:event.target.value}:entry))}>{IDENTITY_VIEWPOINTS.map((view)=><option key={view}>{view}</option>)}</select></label></article>)}<button className="primary" disabled={busy} onClick={beginBatch}>RUN FIRST GATE 0 · {batch.length} SOURCE{batch.length===1?'':'S'}</button></div>:null}</>:null}
      {mode==='CAMERA'||mode==='MICROPHONE'?<div className="capture-box"><p>{mode==='CAMERA'?'Camera video is treated as visual-only identity evidence; audio is not a voice source.':'Microphone audio requires separate voice consent if used as a voice source.'}</p>{capture?.kind===mode?<button className="primary" onClick={()=>capture.recorder.stop()}>STOP &amp; INTAKE</button>:<button className="primary" onClick={()=>startCapture(mode)}>START {mode}</button>}</div>:null}
      {mode==='EXISTING_ASSET'?<div className="form-grid"><Select label="Existing Content Factory artifact" value={existingId} onChange={setExistingId}><option value="">Choose brand-scoped immutable artifact</option>{existing.map((item)=><option value={item.id} key={item.id}>{item.kind} · {item.artifactId} · v{item.artifactVersion}</option>)}</Select><button className="primary" disabled={!existingId||busy} onClick={()=>submitIntake()}>SELECT &amp; RUN GATE 0</button></div>:null}
      {mode==='SAFE_URL_IMPORT'?<div className="form-grid"><Input label="Explicit HTTPS asset URL" value={safeUrl} onChange={setSafeUrl}/><button className="primary" disabled={!safeUrl||busy} onClick={()=>submitIntake()}>SAFE IMPORT &amp; RUN GATE 0</button></div>:null}</div>:null}
    {step===2&&intake?<div className="panel avatar-form"><h2>Gate 0, rights and source roles</h2>{batch.length?<p><strong>Initial source {batchIndex+1} of {batch.length}</strong> · {attachedCount} already attached. Every source remains independent.</p>:null}<div className="intake-preview"><div>{intake.asset.mimeType.startsWith('image/')?<img alt="Avatar source preview" src={intake.asset.previewUrl}/>:intake.asset.mimeType.startsWith('video/')?<video controls src={intake.asset.previewUrl}/>:<audio controls src={intake.asset.previewUrl}/>}</div><dl><dt>Source readiness</dt><dd><Badge value={readiness.state}/><p>{readiness.reason}</p></dd><dt>Gate 0</dt><dd><Badge value={gateStatus}/> · {intake.gate0?.policyVersion||intake.asset.gate0PolicyVersion}</dd><dt>Artifact</dt><dd>{intake.asset.artifactId} · v{intake.asset.artifactVersion}</dd><dt>SHA-256</dt><dd><code>{intake.asset.contentHash}</code></dd><dt>Media</dt><dd>{intake.mediaAnalysis?.originalFilename||intake.asset.originalFilename||'—'} · {intake.asset.byteSize} bytes · {intake.asset.width||'—'}×{intake.asset.height||'—'}</dd><dt>Rights</dt><dd><Badge value={intake.asset.effectiveRightsStatus}/></dd></dl></div>
      <div className="gate-result">{intake.asset.gate0Findings?.length?<ul>{intake.asset.gate0Findings.map((item)=><li key={`${item.severity}:${item.code}`}><strong>{item.code}</strong> · {item.explanation||'Bounded intake policy finding.'}</li>)}</ul>:<span>No blocking or review findings</span>}<code>Paid provider calls: 0 · External generation calls: 0</code></div>
      {gateStatus==='REVIEW'?<div className="review-actions"><button className="secondary" disabled={busy} onClick={()=>review('MARK_RIGHTS_VERIFIED')}>MARK RIGHTS VERIFIED</button><button className="primary" disabled={busy} onClick={()=>review('APPROVE_FOR_USE')}>APPROVE FOR USE</button></div>:null}
      {form.subjectType!=='SYNTHETIC'&&!avatar?.consentEvents?.some((item)=>item.modality==='FACE'&&item.status==='APPROVED')?<div className="consent-capture"><h3>Face consent</h3><p className="warning-panel">One valid scoped FACE consent may cover additional photographs of this same person; it is not copied outside its recorded brand, vertical, channels or use types.</p><div className="form-grid"><Input label="Consenting person identity" value={form.consentName} onChange={(v)=>change('consentName',v)}/><Input label="Rights basis" value={form.consentBasis} onChange={(v)=>change('consentBasis',v)}/><Input label="Consent evidence notes" value={form.consentEvidence} onChange={(v)=>change('consentEvidence',v)}/><label className="check wide"><input aria-label="Consent disclosure accepted" type="checkbox" checked={form.consentDisclosure} onChange={(event)=>change('consentDisclosure',event.target.checked)}/>I showed the explicit consent text before recording or approval.</label></div><div className="review-actions"><button className="secondary" disabled={busy||!form.consentDisclosure} onClick={()=>startCapture('CAMERA',true)}>RECORD LOCAL CONSENT VIDEO</button><button className="secondary" disabled={busy||!form.consentDisclosure} onClick={()=>startCapture('MICROPHONE',true)}>RECORD LOCAL CONSENT AUDIO</button>{capture?.consentEvidence?<button className="primary" onClick={()=>capture.recorder.stop()}>STOP CONSENT RECORDING</button>:null}<button className="secondary" disabled={busy} onClick={requestRemoteConsent}>CREATE REMOTE CONSENT LINK / QR FOUNDATION</button></div>{consentEvidence?<div className="gate-result"><Badge value={consentEvidence.effectiveGate0Status}/><span>Immutable consent evidence · {consentEvidence.mimeType} · {consentEvidence.artifactId} v{consentEvidence.artifactVersion}</span>{consentEvidence.effectiveGate0Status==='REVIEW'?<button onClick={reviewConsentEvidence}>APPROVE CONSENT EVIDENCE</button>:null}</div>:null}{consentLink?<div className="gate-result"><strong>Copy consent link</strong><code>{consentLink.consentPath}</code><span>No message was sent; token state is durable.</span></div>:null}<button className="secondary" disabled={busy||!form.consentDisclosure||(!form.consentEvidence&&consentEvidence?.effectiveGate0Status!=='PASS')} onClick={grantConsent}>RECORD APPEND-ONLY FACE CONSENT</button></div>:null}
      <fieldset className="source-roles"><legend>Explicit source roles</legend>{['IDENTITY','PASSPORT_SOURCE','VOICE_SOURCE','WARDROBE','PRODUCT','LOCATION','STYLE_REFERENCE','PREVIOUS_SHOT'].map((role)=><label key={role}><input type="checkbox" checked={roles.includes(role)} onChange={()=>toggleRole(role)}/>{role.replaceAll('_',' ')}</label>)}</fieldset><button className="primary" disabled={busy||gateStatus!=='PASS'||!roles.length} onClick={useSource}>{batch.length&&batchIndex<batch.length-1?'USE SOURCE & CONTINUE BATCH':'USE AS AVATAR SOURCE'}</button></div>:null}
    {step===3?<div className="panel avatar-form"><h2>Identity</h2><p className="page-note">Approved sources are evidence, not identity text. Clothing, accessories and backgrounds never become identity by accident.</p><div className="form-grid"><Input label="Age presentation" value={form.agePresentation} onChange={(v)=>change('agePresentation',v)}/><Input label="Personality" value={form.personality} onChange={(v)=>change('personality',v)}/><Input label="Languages" value={form.languages} onChange={(v)=>change('languages',v)}/><Input label="Visual direction" value={form.visualDirection} onChange={(v)=>change('visualDirection',v)}/><Input label="Prohibited uses" value={form.prohibitedUses} onChange={(v)=>change('prohibitedUses',v)}/></div><button className="primary" disabled={busy} onClick={saveIdentity}>{busy?'SAVING IDENTITY…':'SAVE IMMUTABLE IDENTITY VERSION'}</button></div>:null}
    {step===4?<div className="panel avatar-form"><h2>Identity Lock</h2><p className="page-note">Classify what is permanent, temporary and uncertain. Source viewpoint labels remain evidence metadata only.</p><label>PERMANENT<textarea aria-label="Wizard Identity Lock permanent" rows="4" value={form.lockPermanent} onChange={(event)=>change('lockPermanent',event.target.value)}/></label><label>TEMPORARY / NON-IDENTITY<textarea aria-label="Wizard Identity Lock temporary" rows="4" value={form.lockTemporary} onChange={(event)=>change('lockTemporary',event.target.value)}/></label><label>UNCERTAIN<textarea aria-label="Wizard Identity Lock uncertain" rows="3" value={form.lockUncertain} onChange={(event)=>change('lockUncertain',event.target.value)}/></label><button className="primary" disabled={busy} onClick={saveIdentityLock}>{busy?'LOCKING…':'SAVE IMMUTABLE IDENTITY LOCK'}</button></div>:null}
    {step===5?<div className="panel avatar-form"><h2>Ready for Passport Lab</h2><Badge value="L0 IDENTITY"/><p>{attachedCount||1} immutable source{(attachedCount||1)===1?'':'s'} attached. Only human certification of a valid Passport candidate can create L1.</p></div>:null}
  </section>;
}
