import React, { useMemo, useState } from 'react';
import { api } from './api';

const ROLES = ['HOOK','TENSION','INSIGHT','ACTION','RESOLUTION','CTA'];
const SHOT_FIELDS = ['purpose','subject','action','environment','emotionalIntent','framing','camera','lensComposition','lighting','continuity','negativeGuidance'];
const CONTINUITY_FIELDS = ['identity','appearance','wardrobe','environment','props','lightingColorLanguage','cameraLanguage'];
const makeShot = (i) => ({ shotId:`shot-${i+1}`,assetId:`video-${i+1}`,durationSeconds:5,roles:i?['RESOLUTION','CTA']:['HOOK','TENSION'],purpose:'',subject:'',action:'',environment:'',emotionalIntent:'',framing:'',camera:'',lensComposition:'',lighting:'',continuity:'',negativeGuidance:'',referencePolicy:'NONE',voiceoverSegment:'' });
const INITIAL = { title:'',objective:'',targetPlatform:'Instagram Reels',targetDurationSeconds:10,hook:'',coreMessage:'',cta:'',audienceIntent:'',creativeConcept:'',visualStyle:'',storyboard:[makeShot(0),makeShot(1)],continuity:{ ...Object.fromEntries(CONTINUITY_FIELDS.map((f)=>[f,''])),referencePolicy:'NONE' },voice:{sourceType:null,provider:'',model:'',voiceId:'',language:'en',instructions:'',approved:false},postProduction:{endTitle:{enabled:false,text:'',startTime:8,duration:2},brandName:''},publicationPolicy:{humanApprovalRequired:true,autoPublish:false} };
const vague = /exactly as specified|operator(?:'s)? (?:creative )?brief|(?:awaits?|requires?) (?:the )?operator input|creative input required|\b(?:tbd|todo|placeholder)\b/i;
const specific = (v,n=2) => { const s=String(v||'').trim(); return !vague.test(s)&&s.split(/\s+/).filter(Boolean).length>=n; };
function validate(b) { const r=new Set(b.storyboard.flatMap((s)=>s.roles)); const pairs=[['SUBJECT SPECIFICITY',b.storyboard.every((s)=>specific(s.subject,3))],['ACTION SPECIFICITY',b.storyboard.every((s)=>specific(s.action,3))],['ENVIRONMENT SPECIFICITY',b.storyboard.every((s)=>specific(s.environment,3))],['EMOTIONAL BEAT',b.storyboard.every((s)=>specific(s.emotionalIntent))],['CAMERA INTENT',b.storyboard.every((s)=>specific(`${s.framing} ${s.camera} ${s.lensComposition}`,5))],['LIGHTING INTENT',b.storyboard.every((s)=>specific(s.lighting))],['SHOT PURPOSE',b.storyboard.length>=2&&b.storyboard.length<=5&&b.storyboard.every((s)=>specific(s.purpose,3))],['STORY ARC',r.has('HOOK')&&(r.has('TENSION')||r.has('INSIGHT'))&&(r.has('ACTION')||r.has('INSIGHT'))&&r.has('RESOLUTION')&&(r.has('CTA')||specific(b.cta))],['CTA RESOLUTION',specific(b.cta)&&(r.has('CTA')||r.has('RESOLUTION'))],['DURATION ALIGNMENT',b.storyboard.reduce((n,s)=>n+Number(s.durationSeconds||0),0)===Number(b.targetDurationSeconds)],['CONTINUITY PLAN',CONTINUITY_FIELDS.every((f)=>specific(b.continuity[f]))]]; return { status:pairs.every(([,p])=>p)?'PASS':'FAIL',checks:pairs.map(([name,p])=>({name,status:p?'PASS':'FAIL'})) }; }
function Field({label,value,onChange,number=false,area=true}) { const Tag=area?'textarea':'input'; return <label>{label}<Tag aria-label={label} type={number?'number':undefined} value={value??''} onChange={(e)=>onChange(number?Number(e.target.value):e.target.value)}/></label>; }

export function CreativeProduction() {
  const [brief,setBrief]=useState(INITIAL),[brands,setBrands]=useState([]),[brandId,setBrandId]=useState(''),[draft,setDraft]=useState(null),[preflight,setPreflight]=useState(null),[preflightInput,setPreflightInput]=useState(null),[preview,setPreview]=useState(null),[message,setMessage]=useState(null),[advanced,setAdvanced]=useState(false),[uploadedFile,setUploadedFile]=useState(null),[attested,setAttested]=useState(false),[video,setVideo]=useState({provider:'',model:'',modelFamily:'',profile:'QUALITY',capability:'TEXT_TO_VIDEO',resolution:'1080x1920',capabilities:['TEXT_TO_VIDEO']});
  React.useEffect(()=>{api('/api/brands').then(setBrands).catch(()=>setBrands([]));},[]);
  const completeness=useMemo(()=>validate(brief),[brief]);
  const edit=(fn,voice=false)=>{setBrief((current)=>{const next=fn(current);return voice?{...next,voice:{...next.voice,approved:false}}:next;});setPreflight(null);};
  const setTop=(name,value)=>edit((b)=>({...b,[name]:value}));
  const setShot=(i,name,value)=>edit((b)=>({...b,storyboard:b.storyboard.map((s,n)=>n===i?{...s,[name]:value}:s)}));
  const move=(i,d)=>edit((b)=>{const a=[...b.storyboard],t=i+d;if(t<0||t>=a.length)return b;[a[i],a[t]]=[a[t],a[i]];return{...b,storyboard:a};});
  const add=()=>brief.storyboard.length<5&&edit((b)=>({...b,storyboard:[...b.storyboard,makeShot(b.storyboard.length)]}));
  const remove=(i)=>brief.storyboard.length>2&&edit((b)=>({...b,storyboard:b.storyboard.filter((_,n)=>n!==i)}));
  const duplicate=(i)=>brief.storyboard.length<5&&edit((b)=>{const a=[...b.storyboard],copy={...a[i],shotId:`shot-copy-${Date.now()}`,assetId:`video-copy-${Date.now()}`};a.splice(i+1,0,copy);return{...b,storyboard:a};});
  async function save(){try{const body={brandId,brief,providerSelection:{},voiceSelection:brief.voice};const value=draft?await api(`/api/v2.10/creative-drafts/${draft.id}`,{method:'PATCH',body:JSON.stringify(body)}):await api('/api/v2.10/creative-drafts',{method:'POST',body:JSON.stringify(body)});setDraft(value);setMessage('Draft saved. External calls: 0.');}catch(e){setMessage(e.message);}}
  async function generatePreview(){const previewText=brief.storyboard.map((s)=>s.voiceoverSegment).filter(Boolean).join(' ');if(!window.confirm(`GENERATE VOICE PREVIEW\nProvider: ${brief.voice.provider}\nModel: ${brief.voice.model}\nVoice: ${brief.voice.voiceId}\nPreview text: ${previewText}\nKnown cost: UNKNOWN\nExternal calls: 1`))return;try{const value=await api(`/api/v2.10/creative-drafts/${draft.id}/voice-preview`,{method:'POST',body:JSON.stringify({brandId,voice:brief.voice,previewText,confirmation:true})});setPreview(value.artifact);setMessage(value.reused?'Cached preview reused. External calls: 0.':'Preview generated. External calls: 1.');}catch(e){setMessage(e.message);}}
  async function runPreflight(){const input={brief,video,quality:{semanticCritic:'configured-semantic-critic',semanticCalls:1,otherEvaluatorCalls:0},master:{profile:'SOCIAL_VERTICAL',resolution:'1080x1920',fps:30,audioStrategy:brief.voice.sourceType}};try{const value=await api(`/api/v2.10/creative-drafts/${draft.id}/preflight`,{method:'POST',body:JSON.stringify({brandId,...input})});setPreflight(value);setPreflightInput(input);}catch(e){setMessage(e.message);}}
  async function useVoice(){try{const value=await api(`/api/v2.10/creative-drafts/${draft.id}/voice-approve`,{method:'POST',body:JSON.stringify({brandId,voice:brief.voice,previewArtifact:preview})});setDraft(value);setBrief(value.creative_brief||value.creativeBrief);setMessage('Exact voice configuration and preview approved.');}catch(e){setMessage(e.message);}}
  async function uploadVoice(){if(!uploadedFile||!attested)return;const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(uploadedFile);});try{const artifact=await api(`/api/v2.10/creative-drafts/${draft.id}/voice-upload`,{method:'POST',body:JSON.stringify({brandId,contentBase64:data,contentType:uploadedFile.type,operatorAttestation:{confirmed:true,text:'The uploaded narration matches the approved spoken copy.',actor:'dashboard-operator',confirmedAt:new Date().toISOString()}})});const exact={artifactId:artifact.id,durationSeconds:Number(artifact.duration_seconds),contentHash:artifact.content_hash,localUrl:preview?.localUrl};setPreview(exact);edit((b)=>({...b,voice:{...b.voice,sourceType:'UPLOADED_AUDIO',uploadedArtifactId:artifact.id,previewArtifact:exact}}),true);setMessage('Immutable uploaded narration stored and locally previewable. External calls: 0.');}catch(e){setMessage(e.message);}}
  async function start(){if(!window.confirm(`START PRODUCTION?\nMaximum external calls: ${preflight.externalCalls.maximum}\nKnown cost: ${preflight.costStatus}\nHuman approval: REQUIRED\nAuto publish: NO`))return;try{await api(`/api/v2.10/creative-drafts/${draft.id}/start`,{method:'POST',body:JSON.stringify({brandId,currentInput:preflightInput,confirmation:true})});setMessage('Production start accepted. Human review remains required.');}catch(e){setMessage(e.message);}}
  return <main><header className="page-header"><span className="eyebrow">V2.10 · ZERO-CALL EDITING</span><h1>Creative Production</h1></header><p className="page-note">Review the resolved advertisement and exact voice before any paid generation.</p>{message&&<div className="notice">{message}</div>}<div className="production-form">
    <section className="panel"><h2 className="panel-title">CREATIVE BRIEF</h2><div className="form-grid"><label>Brand<select aria-label="Creative brand" value={brandId} onChange={(e)=>{setBrandId(e.target.value);setDraft(null);setPreflight(null);}}><option value="">Choose brand</option>{brands.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{[['title','TITLE'],['objective','OBJECTIVE'],['targetPlatform','TARGET PLATFORM'],['targetDurationSeconds','TARGET DURATION SECONDS'],['hook','HOOK'],['coreMessage','CORE MESSAGE'],['cta','CTA'],['audienceIntent','AUDIENCE INTENT'],['creativeConcept','CREATIVE CONCEPT'],['visualStyle','VISUAL STYLE']].map(([n,l])=><Field key={n} label={l} value={brief[n]} number={n==='targetDurationSeconds'} area={!['title','targetPlatform','targetDurationSeconds'].includes(n)} onChange={(v)=>setTop(n,v)}/>)}</div></section>
    <section className="panel"><div className="section-head"><h2 className="panel-title">STORYBOARD · {brief.storyboard.length} SHOTS</h2><button className="secondary" type="button" disabled={brief.storyboard.length>=5} onClick={add}>ADD SHOT</button></div>{brief.storyboard.map((s,i)=><article className="shot-card" key={s.shotId}><div className="shot-head"><strong>SHOT {i+1} · {s.durationSeconds} sec</strong><div><button type="button" disabled={!i} onClick={()=>move(i,-1)}>MOVE SHOT UP</button><button type="button" disabled={i===brief.storyboard.length-1} onClick={()=>move(i,1)}>MOVE SHOT DOWN</button><button type="button" disabled={brief.storyboard.length>=5} onClick={()=>duplicate(i)}>DUPLICATE SHOT</button><button type="button" disabled={brief.storyboard.length<=2} onClick={()=>remove(i)}>REMOVE SHOT</button></div></div><div className="role-row"><span>ROLE</span>{ROLES.map((r)=><label key={r}><input type="checkbox" checked={s.roles.includes(r)} onChange={(e)=>setShot(i,'roles',e.target.checked?[...s.roles,r]:s.roles.filter((v)=>v!==r))}/>{r}</label>)}</div><div className="form-grid"><Field label="DURATION SECONDS" number area={false} value={s.durationSeconds} onChange={(v)=>setShot(i,'durationSeconds',v)}/>{SHOT_FIELDS.map((n)=><Field key={n} label={n.replaceAll(/([A-Z])/g,' $1').toUpperCase()} value={s[n]} onChange={(v)=>setShot(i,n,v)}/>)}<label>REFERENCE<select aria-label={`Shot ${i+1} reference`} value={s.referencePolicy} onChange={(e)=>setShot(i,'referencePolicy',e.target.value)}><option>NONE</option><option>PREVIOUS_SHOT_FRAME</option><option>UPLOADED_REFERENCE</option></select></label><Field label="VOICEOVER SEGMENT" value={s.voiceoverSegment} onChange={(v)=>setShot(i,'voiceoverSegment',v)}/></div></article>)}</section>
    <section className="panel"><h2 className="panel-title">CONTINUITY</h2><div className="form-grid">{CONTINUITY_FIELDS.map((n)=><Field key={n} label={n.replaceAll(/([A-Z])/g,' $1').toUpperCase()} value={brief.continuity[n]} onChange={(v)=>edit((b)=>({...b,continuity:{...b.continuity,[n]:v}}))}/>)}<label>REFERENCE POLICY<select value={brief.continuity.referencePolicy} onChange={(e)=>edit((b)=>({...b,continuity:{...b.continuity,referencePolicy:e.target.value}}))}><option>NONE</option><option>PREVIOUS_SHOT_FRAME</option><option>UPLOADED_REFERENCE</option></select></label></div></section>
    <section className="panel"><h2 className="panel-title">VOICE STUDIO</h2><div className="form-grid"><label>Source type<select aria-label="Voice source type" value={brief.voice.sourceType||''} onChange={(e)=>edit((b)=>({...b,voice:{...b.voice,sourceType:e.target.value||null}}),true)}><option value="">VOICE SELECTION REQUIRED</option><option>AI_PRESET</option><option>PROVIDER_CUSTOM</option><option>UPLOADED_AUDIO</option></select></label>{['provider','model','voiceId','language','instructions'].map((n)=><Field key={n} label={n.toUpperCase()} value={brief.voice[n]} area={n==='instructions'} onChange={(v)=>edit((b)=>({...b,voice:{...b.voice,[n]:v}}),true)}/>)}<label>UPLOAD AUDIO<input aria-label="Upload audio" type="file" accept="audio/wav,audio/mpeg,audio/mp4" onChange={(e)=>{const file=e.target.files?.[0];if(file){setUploadedFile(file);setPreview({localUrl:URL.createObjectURL(file)});setMessage('Local audio preview ready. External calls: 0. Attestation remains required.');}}}/></label>{brief.voice.sourceType==='PROVIDER_CUSTOM'&&<><label className="check"><input type="checkbox" checked={brief.voice.consent?.confirmed||false} onChange={(e)=>edit((b)=>({...b,voice:{...b.voice,consent:{required:true,confirmed:e.target.checked,ownerRelationship:'SELF',confirmedAt:new Date().toISOString(),actor:'dashboard-operator'}}}),true)}/> I confirm explicit custom/cloned voice consent</label><label>Owner relationship<select value={brief.voice.consent?.ownerRelationship||'SELF'} onChange={(e)=>edit((b)=>({...b,voice:{...b.voice,consent:{...b.voice.consent,required:true,ownerRelationship:e.target.value}}}),true)}><option>SELF</option><option>THIRD_PARTY</option></select></label></>}</div>{preview?.localUrl&&<audio controls src={preview.localUrl}/>}<label className="check"><input type="checkbox" checked={attested} onChange={(e)=>setAttested(e.target.checked)}/> The uploaded narration matches the approved spoken copy.</label><div className="actions"><button type="button" className="secondary" disabled={!draft||!brief.voice.provider||!brief.voice.model||!brief.voice.voiceId} onClick={generatePreview}>GENERATE VOICE PREVIEW</button><button type="button" className="secondary" disabled={!draft||!uploadedFile||!attested} onClick={uploadVoice}>UPLOAD AUDIO AS IMMUTABLE EVIDENCE</button><button type="button" className="secondary" disabled={!preview||!draft||Boolean(uploadedFile&&!brief.voice.uploadedArtifactId)} onClick={useVoice}>USE THIS VOICE</button></div><p className="boundary">Voice changes invalidate approval. Custom voices require consent; uploaded narration requires explicit spoken-copy attestation.</p></section>
    <section className="panel"><h2 className="panel-title">POST PRODUCTION</h2><label className="check"><input type="checkbox" checked={brief.postProduction.endTitle.enabled} onChange={(e)=>edit((b)=>({...b,postProduction:{...b.postProduction,endTitle:{...b.postProduction.endTitle,enabled:e.target.checked}}}))}/> End title enabled</label><div className="form-grid">{['text','startTime','duration'].map((n)=><Field key={n} label={`END TITLE ${n.toUpperCase()}`} area={false} number={n!=='text'} value={brief.postProduction.endTitle[n]} onChange={(v)=>edit((b)=>({...b,postProduction:{...b.postProduction,endTitle:{...b.postProduction.endTitle,[n]:v}}}))}/>)}<Field label="BRAND NAME" area={false} value={brief.postProduction.brandName} onChange={(v)=>edit((b)=>({...b,postProduction:{...b.postProduction,brandName:v}}))}/></div><p>Approved text is rendered only by FFmpeg and excluded from paid video prompts.</p></section>
    <section className="panel"><h2 className="panel-title">CREATIVE VALIDATION</h2><div className="validation-grid">{completeness.checks.map((c)=><div key={c.name}><span>{c.name}</span><strong className={c.status.toLowerCase()}>{c.status}</strong></div>)}</div></section>
    <div className="actions"><button type="button" className="primary" disabled={!brandId} onClick={save}>SAVE DRAFT</button><button type="button" className="primary" disabled={!draft} onClick={runPreflight}>FINAL PRODUCTION PREFLIGHT</button></div>
    <section className="panel"><h2 className="panel-title">PRODUCTION PREFLIGHT</h2><div className="form-grid"><Field label="VIDEO PROVIDER" area={false} value={video.provider} onChange={(value)=>{setVideo({...video,provider:value});setPreflight(null);}}/><Field label="VIDEO MODEL" area={false} value={video.model} onChange={(value)=>{setVideo({...video,model:value});setPreflight(null);}}/><Field label="VIDEO MODEL FAMILY" area={false} value={video.modelFamily} onChange={(value)=>{setVideo({...video,modelFamily:value});setPreflight(null);}}/><Field label="VIDEO PROFILE" area={false} value={video.profile} onChange={(value)=>{setVideo({...video,profile:value});setPreflight(null);}}/><label className="check"><input type="checkbox" checked={video.capabilities.includes('IMAGE_TO_VIDEO')} onChange={(e)=>{setVideo({...video,capabilities:e.target.checked?['TEXT_TO_VIDEO','IMAGE_TO_VIDEO']:['TEXT_TO_VIDEO']});setPreflight(null);}}/> Provider/model supports image-to-video continuity</label></div>{preflight?<><div className="plan-grid"><div className="key-value"><span>CREATIVE</span><p>{preflight.creative.storyboardShots} shots · {preflight.creative.completeness} · arc {preflight.creative.storyArc}</p></div><div className="key-value"><span>EXTERNAL CALL ACCOUNTING</span><p>Video {preflight.externalCalls.video} · Speech {preflight.externalCalls.speech} · Semantic {preflight.externalCalls.semantic} · Maximum {preflight.externalCalls.maximum}</p></div><div className="key-value"><span>POLICY</span><p>HUMAN APPROVAL REQUIRED · AUTO PUBLISH NO · COST {preflight.costStatus}</p></div></div><button className="start" onClick={start} disabled={preflight.status!=='READY'||completeness.status==='FAIL'||!brief.voice.approved}>START PRODUCTION</button></>:<p>No current preflight. Creative, provider, storyboard, or voice edits invalidate its fingerprint.</p>}</section>
    <button type="button" className="advanced-toggle" onClick={()=>setAdvanced(!advanced)}>Advanced / Technical {advanced?'−':'+'}</button>{advanced&&<pre className="canonical">{JSON.stringify(brief,null,2)}</pre>}
  </div></main>;
}
