import React,{useState}from'react';
import {api}from './api';
const permanent=['faceShape','eyes','nose','mouthLips','jawChin','skinTone','hairline'];
const temporary=['clothing','accessories','background','lighting','facialExpression','temporaryHairstyle'];
const label=v=>v.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
export function IdentityLockBuild({avatar,brandId,onPassport,onBack}){const [p,setP]=useState({}),[t,setT]=useState({}),[notes,setNotes]=useState(''),[confirmed,setConfirmed]=useState(false),[saved,setSaved]=useState(null),[error,setError]=useState(null);const toggle=(set,key)=>set(x=>({...x,[key]:!x[key]}));const save=async()=>{try{const result=await api(`/api/avatar-studio/avatars/${avatar.id}/identity-locks`,{method:'POST',body:JSON.stringify({brandId,permanent:Object.fromEntries(Object.entries(p).filter(([,v])=>v).map(([k])=>[k,'explicit human classification'])),temporary:Object.fromEntries(Object.entries(t).filter(([,v])=>v).map(([k])=>[k,'temporary / do not lock'])),uncertain:notes?{notes}: {},notes,humanApproval:true,provenance:{source:'AVATAR_STUDIO_V1_CANONICAL_BUILD'}})});setSaved(result.identityLock)}catch(e){setError(e)}};const evidence=(avatar.sources||[]).filter(s=>(s.roles||[]).includes('IDENTITY'));
if((avatar.identityLocks||[]).some(l=>l.identityVersionId===avatar.identityVersionId))return <section className="panel avatar-form"><h2>IDENTITY LOCK</h2><strong>IDENTITY LOCK SAVED</strong><p>This current Identity Lock is immutable.</p><button className="primary" onClick={onPassport}>CONTINUE TO PASSPORT LAB</button></section>;
return <section className="panel avatar-form"><h2>IDENTITY LOCK</h2><p><strong>{avatar.internalName}</strong> · STRONG IDENTITY COVERAGE · FACE CONSENT APPROVED</p><div className="v1-photo-choices">{evidence.map(s=><article className="v1-selected-photo" key={s.id}><img alt={`${s.effectiveViewpoint} identity evidence`} src={`/api/avatar-studio/intakes/${s.intakeAssetId}/content?brandId=${brandId}&avatarId=${avatar.id}`}/><strong>{label(s.effectiveViewpoint)}</strong></article>)}</div><h3>Permanent / preserve</h3>{permanent.map(k=><label key={k}><input type="checkbox" checked={!!p[k]} onChange={()=>toggle(setP,k)}/>{label(k)}</label>)}<h3>Temporary / do not lock as identity</h3>{temporary.map(k=><label key={k}><input type="checkbox" checked={!!t[k]} onChange={()=>toggle(setT,k)}/>{label(k)}</label>)}<label>Uncertain notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm these classifications describe the stable identity and are supported by the displayed source evidence.</label>{error&&<p className="error-panel">{error.message}</p>}{saved?<><strong>IDENTITY LOCK SAVED</strong><button className="primary" onClick={onPassport}>CONTINUE TO PASSPORT LAB</button></>:<button className="primary" disabled={!confirmed||!Object.values(p).some(Boolean)} onClick={save}>SAVE IMMUTABLE IDENTITY LOCK</button>}<button className="secondary" onClick={onBack}>BACK TO IDENTITY EVIDENCE</button></section>;
}
