import React, { useEffect, useState } from 'react';
import { api } from './api';

export function MotionPilot({ brands }) {
  const [brandId,setBrandId]=useState(''); const [avatars,setAvatars]=useState([]); const [avatarId,setAvatarId]=useState(''); const [avatar,setAvatar]=useState(null); const [plan,setPlan]=useState(null); const [execution,setExecution]=useState(null); const [budget,setBudget]=useState('1.00'); const [error,setError]=useState(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!brandId){setAvatars([]);return;}api(`/api/avatar-studio/avatars?brandId=${encodeURIComponent(brandId)}`).then(setAvatars).catch(setError);},[brandId]);
  useEffect(()=>{if(!avatarId||!brandId)return;api(`/api/avatar-studio/avatars/${avatarId}?brandId=${encodeURIComponent(brandId)}`).then(setAvatar).catch(setError);},[avatarId,brandId]);
  const scope=()=>({workspaceId:avatar.workspaceId,brandId,vertical:avatar.vertical||avatar.verticalCode,identityVersionId:avatar.identityVersionId});
  async function createPlan(){setBusy(true);setError(null);try{setPlan(await api(`/api/avatar-studio/avatars/${avatar.id}/motion-pilot-plans`,{method:'POST',body:JSON.stringify(scope())}));}catch(e){setError(e)}finally{setBusy(false)}}
  async function preflight(){setBusy(true);setError(null);try{setExecution(await api(`/api/avatar-studio/avatars/${avatar.id}/motion-pilot-plans/${plan.id}/preflight`,{method:'POST',body:JSON.stringify({...scope(),maximumAllowedCost:Number(budget)})}));}catch(e){setError(e)}finally{setBusy(false)}}
  async function approve(){setBusy(true);setError(null);try{const approved=await api(`/api/avatar-studio/avatars/${avatar.id}/motion-pilot-executions/${execution.executionId}/approve`,{method:'POST',body:JSON.stringify({...scope(),explicitConfirmation:true,unknownCostAcknowledged:['UNKNOWN','PARTIAL'].includes(execution.costPlan?.status)})});setExecution({...execution,...approved})}catch(e){setError(e)}finally{setBusy(false)}}
  async function generate(){setBusy(true);setError(null);try{setExecution({...execution,...await api(`/api/avatar-studio/avatars/${avatar.id}/motion-pilot-executions/${execution.executionId}/generate`,{method:'POST',body:JSON.stringify(scope())})})}catch(e){setError(e)}finally{setBusy(false)}}
  async function recoverLocal(){const attempt=error?.details?.motionPilotAttempt;if(!attempt)return;setBusy(true);try{setExecution({...execution,...await api(`/api/avatar-studio/avatars/${avatar.id}/motion-pilot-executions/${attempt.executionId}/recover-local-output`,{method:'POST',body:JSON.stringify({...scope(),attemptId:attempt.id})})});setError(null)}catch(e){setError(e)}finally{setBusy(false)}}
  const failedAttempt=error?.details?.motionPilotAttempt;
  return <section className="passport-lab"><section className="panel"><h2>AVATAR MOTION PILOT</h2><p>One technical, silent, chest-up identity/motion proof. This workflow never certifies or requires the full L2 pack.</p><label>Brand<select value={brandId} onChange={(e)=>{setBrandId(e.target.value);setAvatarId('')}}><option value="">Choose brand</option>{brands.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Avatar<select value={avatarId} onChange={(e)=>setAvatarId(e.target.value)}><option value="">Choose avatar</option>{avatars.map((x)=><option key={x.id} value={x.id}>{x.internalName}</option>)}</select></label>{error?<div className="error-panel"><strong>{error.code}</strong><p>{error.message}</p>{failedAttempt?<><p>PROVIDER: {String(failedAttempt.providerStatus||'unknown').toUpperCase()} · RAW OUTPUT: {failedAttempt.rawOutputSaved?'SAVED':'NOT SAVED'} · DOWNSTREAM: FAILED</p><p>FAILURE: {failedAttempt.failureClassification}</p>{failedAttempt.rawOutputSaved?<button className="primary" disabled={busy} onClick={recoverLocal}>RECOVER FROM LOCAL OUTPUT · ZERO CALLS</button>:null}</>:null}</div>:null}{avatar?<button className="primary" disabled={busy} onClick={createPlan}>PLAN MOTION PILOT · ZERO CALLS</button>:null}</section>{plan?<section className="panel"><h3>REFERENCE-TO-VIDEO IDENTITY PILOT</h3><p>Replicate · wan-video/wan-2.7-r2v · REFERENCE_TO_VIDEO · 5s · 720p · 9:16 · single shot · 1 planned call · $0.50</p><h4>EXACT PROVIDER REFERENCES</h4>{(plan.identityReferenceBundle?.references||[]).map((ref)=><article key={ref.intakeId}><img alt={`${ref.role} ${ref.viewpoint}`} src={`/api/avatar-studio/intakes/${encodeURIComponent(ref.intakeId)}/content?brandId=${encodeURIComponent(brandId)}&avatarId=${encodeURIComponent(avatar.id)}`} /><p>{ref.role} / {ref.viewpoint} · {ref.intakeId} · {String(ref.contentHash).slice(0,12)} · {ref.byteSize} bytes</p></article>)}<p>REFERENCE BUNDLE FINGERPRINT: {plan.identityReferenceBundle?.bundleFingerprint}</p><label>maximumAllowedCost<input value={budget} onChange={(e)=>setBudget(e.target.value)} /></label><button className="primary" disabled={busy} onClick={preflight}>ZERO-CALL PREFLIGHT</button></section>:null}{execution?<section className="panel"><h3>{execution.status}</h3><p>Human approval required. Provider calls executed: {execution.providerCalls||0}.</p><button className="primary" disabled={busy||execution.status==='APPROVED'} onClick={approve}>APPROVE EXACT PILOT</button>{execution.status==='APPROVED'?<><p>PAID CALL · {plan.route.provider} / {plan.route.model} · 1 call · known cost $0.50 · maximumAllowedCost ${budget}</p><button className="regenerate" disabled={busy} onClick={generate}>GENERATE 1 REAL VIDEO</button></>:null}</section>:null}</section>;
}
