'use strict';

const CAPABILITIES = Object.freeze({
  TEXT_TO_VIDEO: 'TEXT_TO_VIDEO',
  IMAGE_TO_VIDEO: 'IMAGE_TO_VIDEO',
  REFERENCE_TO_VIDEO: 'REFERENCE_TO_VIDEO',
  VIDEO_TO_VIDEO: 'VIDEO_TO_VIDEO',
  VIDEO_EXTENSION: 'VIDEO_EXTENSION',
  FIRST_FRAME_IMAGE_TO_VIDEO: 'FIRST_FRAME_IMAGE_TO_VIDEO',
  FIRST_LAST_FRAME_VIDEO: 'FIRST_LAST_FRAME_VIDEO',
  MULTIMODAL_REFERENCE: 'MULTIMODAL_REFERENCE',
  REFERENCE_IMAGE: 'REFERENCE_IMAGE',
  REFERENCE_VIDEO: 'REFERENCE_VIDEO',
  REFERENCE_AUDIO: 'REFERENCE_AUDIO',
  VIDEO_EDITING: 'VIDEO_EDITING',
  NATIVE_AUDIO_GENERATION: 'NATIVE_AUDIO_GENERATION',
  SEED_CONTROL: 'SEED_CONTROL',
  ADAPTIVE_ASPECT_RATIO: 'ADAPTIVE_ASPECT_RATIO',
  VIDEO_OUTPUT: 'VIDEO_OUTPUT',
  TEXT_TO_IMAGE: 'TEXT_TO_IMAGE',
  IMAGE_TO_IMAGE: 'IMAGE_TO_IMAGE',
  MULTI_VIEW_IDENTITY_REFERENCE: 'MULTI_VIEW_IDENTITY_REFERENCE',
  CHARACTER_BODY_REFERENCE: 'CHARACTER_BODY_REFERENCE',
  CHARACTER_EXPRESSION_REFERENCE: 'CHARACTER_EXPRESSION_REFERENCE',
  MOUTH_SHAPE_REFERENCE: 'MOUTH_SHAPE_REFERENCE',
  SPEECH: 'SPEECH',
  MUSIC: 'MUSIC',
  NATIVE_AUDIO: 'NATIVE_AUDIO',
  NATIVE_DIALOGUE: 'NATIVE_DIALOGUE',
  NATIVE_AMBIENCE: 'NATIVE_AMBIENCE',
  AUDIO_DISABLE_SUPPORTED: 'AUDIO_DISABLE_SUPPORTED',
  HYBRID_AUDIO_SUPPORTED: 'HYBRID_AUDIO_SUPPORTED',
  FAST_RENDER: 'FAST_RENDER',
});

const LEGACY = Object.freeze({
  'video-generation': CAPABILITIES.TEXT_TO_VIDEO,
  'image-generation': CAPABILITIES.TEXT_TO_IMAGE,
  'speech-generation': CAPABILITIES.SPEECH,
  'audio-generation': CAPABILITIES.MUSIC,
});

function normalizeCapability(value) {
  const raw = String(value || '').trim();
  const legacy = LEGACY[raw.toLowerCase().replace(/_/g, '-')];
  const normalized = legacy || raw.toUpperCase().replace(/[ -]+/g, '_');
  if (!Object.hasOwn(CAPABILITIES, normalized)) {
    const error = new Error(`Unsupported canonical capability '${value}'`);
    error.code = 'CAPABILITY_UNSUPPORTED';
    throw error;
  }
  return normalized;
}

module.exports = { CAPABILITIES, LEGACY, normalizeCapability };
